### ISSUE TITLE
MIDI library v5.0 and above

### ISSUE THREAD

**Issue by jamescaf** [jkrame1/Betweener#2]
Hello,
Thanks for making this such an easy and well-documented build and installation. I noticed that the Teensyduino Betweener library wouldn't work with the MIDI library v5.0 and above (I neglected to copy the error messages, my apologies, but they seemed to center around the endTransmission() lines and similar in the Betweener library). If I manually installed MIDI library v4.3.1, the example Arduino sketches worked perfectly. Thanks again!

**Comment by jkrame1** [comment]
Hello James,
Thanks so much for the note. I have a guess about the cause of this and will look into ASAP. Thanks again.

**Comment by jkrame1** [comment]
The current version of the library now works in its default settings with the FortySevenEffects MIDI library v5.x. The DIN MIDI features that were incompatible have now been turned off by default. The plan is to update the hardware midi portion of the library soon to bring the full feature set back.

**Comment by jamescaf** [comment]
Great, thanks!
