### ISSUE TITLE
Question about reprogramming when powering from Eurorack power supply

### ISSUE THREAD

**Issue by jamescaf** [jkrame1/Betweener#3]
Hello,
Feel free to delete or close if this is outside the scope for github issues. If I have the USB breakout connected to the front panel, and I cut the trace on the teensy and set the power jumper to use the 5V regulator in order to power the unit in my eurorack case, will I still be able to reprogram my teensy using the USB connector on the front panel while powering it from a eurorack power supply? Thanks!

**Comment by jkrame1** [comment]
Hello @jamescaf! Yes! The same data lines that carry the MIDI are used for programming and reprogramming. So if the front panel breakout is wired correctly for MIDI then it is wired correctly for programming regardless of how the Teensy is getting powered.

**Comment by jamescaf** [comment]
Awesome, thanks!
